# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee1415abdb48987ab54c84454331a9e7e3c0bbb38623e404d5ae5f21276a3f5c0104c7a86b4b6552d33d3756ad07526b56cab3d61ce899ffa4ab1b32e58ceae3

test:
  secret_key_base: 3bde3316bb5d57b70411ce9159a99004194817e19186501be7cb7b92aa6609cc1b248dc95fb9a907f92d0629788792023763c19503527f5101eb11fc35bc144d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
